### ISSUE TITLE
Testing TROVA with Testdata fails due to processing partposit files

### ISSUE THREAD

**Issue by laroith** [tramo-ephyslab/TROVA-master#1]
When I try the suggested tests with data retrieved from https://zenodo.org/records/10139577 I see two issues:

Input documents line 54: totaltime = 14400 [min]
the testdata are only available for 18 hours = 1080 minutes, or 24 hours = 1440 minutes respectively
also in line 64 ndays = 1 could be to much for 18 hours of tracking.

I tried setting the totaltime = 1440 and used the input_backward_ERAI.cfg file with the correct paths but after a while I get the following message: 

----------------------------------- RUN INFORMATION ------------------------------------

+ Configuration file ->  /home/lar/trova_test/TROVA-master/Inputs/input_backward_ERAI.cfg
+ You are using methodology of Stohl and James (2005) (DOI:10.1175/1525-7541(2004)005<0656:ALAOTA>2.0.CO;2)
+ Target region ->  CAN
+ CPUs for tracking ->   1
+ Tracking mode -> backward
+ Simulation starts -> 2014-10-17 00:00:00
+ Lagrangian Model -> FLEXPART
+ Filter precipitating parcels -> False
+ Filter parcels by height -> False
+ Mask file -> /home/lar/trova_test/TROVA-master/Masks/CAN.nc

AUXILIAR TOOLS
--------------
+ Save parcels' positions at each time step -> False
+ Save dqdt at each dt -> False
+ Plot identified parcels within the target region at time t0 -> False
+ Plot identified parcels trajectories on a map -> False
+ Plot 3D parcels trajectories -> False
                                                                                          
------------------------------------------------------------------------------------------
                              PROCESSING PARTPOSIT FILES                                  
------------------------------------------------------------------------------------------
Bye :)
/home/lar/trova_test/data_test/partposit_20141015180000-> not exits
Bye :)
Bye :)
/home/lar/trova_test/data_test/partposit_20141015180000-> not exits
/home/lar/trova_test/data_test/partposit_20141015180000-> not exits
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
Bye :)
/home/lar/trova_test/data_test/partposit_20141015180000-> not exits
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33520,1],0]
  Exit code:    1
--------------------------------------------------------------------------

When I changed the starting date to 2014.10.19 i got a similar message:

----------------------------------- RUN INFORMATION ------------------------------------

+ Configuration file ->  /home/lar/trova_test/TROVA-master/Inputs/input_backward_ERAI.cfg
+ You are using methodology of Stohl and James (2005) (DOI:10.1175/1525-7541(2004)005<0656:ALAOTA>2.0.CO;2)
+ Target region ->  CAN
+ CPUs for tracking ->   1
+ Tracking mode -> backward
+ Simulation starts -> 2014-10-19 00:00:00
+ Lagrangian Model -> FLEXPART
+ Filter precipitating parcels -> False
+ Filter parcels by height -> False
+ Mask file -> /home/lar/trova_test/TROVA-master/Masks/CAN.nc

AUXILIAR TOOLS
--------------
+ Save parcels' positions at each time step -> False
+ Save dqdt at each dt -> False
+ Plot identified parcels within the target region at time t0 -> False
+ Plot identified parcels trajectories on a map -> False
+ Plot 3D parcels trajectories -> False
                                                                                          
------------------------------------------------------------------------------------------
                              PROCESSING PARTPOSIT FILES                                  
------------------------------------------------------------------------------------------
Bye :)
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits
Bye :)
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits
Bye :)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits
Bye :)
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33710,1],1]
  Exit code:    1
--------------------------------------------------------------------------

There seems to be a problem with stopping the process after the desired runtime.

**Comment by jcfernandez1993** [comment]
Please,
you need to change the following parameter file_gz = 1 because the files in the zenodo repository are compressed.

Or simply decompress the files keeping the parameter file_gz=0.

It should work like this.

**Comment by laroith** [comment]
I have already decompressed the files before, and have file_gz = 0 in agreement with what you are recommending.
I think the problem has more to do with the runtime, as i get several of these messages before the abortion of the job I put up there:

--------------------------------TROVA has started-----------------------------------------
 *****************************************************************************************
 *                    EPhysLab (Environmental Physics Laboratory)                        *
 *                        TRansport Of water VApor (TROVA)                               *
 *                             Version 1.1 (03-11-2023)                                  *
 *                        _____ __    ____                                               *
 *                          |  |  |  /    \ \        //\                                 *
 *                          |  |__| /      \ \      //__\                                *
 *                          |  |  \ \      /  \    //    \                               *
 *                          |  |   \ \____/    \__//      \                              *
 *                                                                                       *
 *                            Edificio Campus da Auga                                    *
 *                               University of Vigo                                      *
 *                                ephyslab.uvigo.es                                      *
 *  contact: jose.carlos.fernandez.alvarez@uvigo.es, albenis.perez.alarcon@uvigo.es      *
 *****************************************************************************************
------------------------------------------------------------------------------------------
                                                                                          
----------------------------------- RUN INFORMATION ------------------------------------

+ Configuration file ->  /home/lar/trova_test/TROVA-master/Inputs/input_backward_ERAI.cfg
+ You are using methodology of Stohl and James (2005) (DOI:10.1175/1525-7541(2004)005<0656:ALAOTA>2.0.CO;2)
+ Target region ->  CAN
+ CPUs for tracking ->   1
+ Tracking mode -> backward
+ Simulation starts -> 2014-10-17 00:00:00
+ Lagrangian Model -> FLEXPART
+ Filter precipitating parcels -> False
+ Filter parcels by height -> False
+ Mask file -> /home/lar/trova_test/TROVA-master/Masks/CAN.nc

AUXILIAR TOOLS
--------------
+ Save parcels' positions at each time step -> False
+ Save dqdt at each dt -> False
+ Plot identified parcels within the target region at time t0 -> False
+ Plot identified parcels trajectories on a map -> False
+ Plot 3D parcels trajectories -> False
                                                                                          
------------------------------------------------------------------------------------------
                              PROCESSING PARTPOSIT FILES                                  
------------------------------------------------------------------------------------------

**Comment by tramo-ephyslab** [comment]
But what errors do you receive now because I don't see them.

Where are you running the code?

**Comment by laroith** [comment]
The error from my first message: 
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits
Bye :)
Primary job terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits
Bye :)

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:
Process name: [[33710,1],1]
Exit code: 1


appears after 3 blocks of RUN INFORMATION that I posted here: https://github.com/tramo-ephyslab/TROVA-master/issues/1#issuecomment-1866135435


I am running the code on a debian linux local server.

**Comment by tramo-ephyslab** [comment]
It still doesn't run because it can't find that file
/home/lar/trova_test/data_test/partposit_20141017180000-> not exits

Please initialize the run with the following parameters:

#Total time for parcel tracking (minutes) [int]
totaltime = 14400
#Start date for tracking [int]
year = 2014
month = 10
day = 18
hour = 00
min = 00

This needs to have a file from October 8 to October 18, 2014. You have to download all the files that are available in the repository.
Also, use at least 4 as the CPU number (parallel running) so that it runs faster because it is using 1 CPU (serial running).

**Comment by laroith** [comment]
In the database: https://zenodo.org/records/10139577 there are 9 files available corresponding to:
6.10.2014 00:00, 06:00, 12:00, 18:00
18.10.2023 00:00, 06:00, 12:00, 18:00
19.10.2023 00:00

I got all of them unziped in the /data_test/ directory.

Could it be a problem that there's many timesteps missing?

**Comment by tramo-ephyslab** [comment]
You have to download the two versions of databases that are available in the Zenodo repository. This is how you complete the missing files

**Comment by laroith** [comment]
thank you that solved my issue
